# Generated by Django 5.1.1 on 2024-09-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='GroupPermission',  # The model containing the field
            old_name='rid',  # Old column name
            new_name='group_id',  # New column name
        ),
        migrations.RenameField(
            model_name='GroupPermission',  # The model containing the field
            old_name='mid',  # Old column name
            new_name='module_id',  # New column name
        ),
        migrations.RenameField(
            model_name='GroupPermission',  # The model containing the field
            old_name='mpid',  # Old column name
            new_name='module_parent_id',  # New column name
        ),
        migrations.RenameField(
            model_name='Module',  # The model containing the field
            old_name='pid',  # Old column name
            new_name='parent_id',  # New column name
        ),
    ]
