# Generated by Django 5.1.1 on 2024-09-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20240926_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='GroupPermission',  # The model containing the field
            old_name='group_id',  # Old column name
            new_name='group',  # New column name
        ),
        migrations.RenameField(
            model_name='GroupPermission',  # The model containing the field
            old_name='module_id',  # Old column name
            new_name='module',  # New column name
        ),
    ]
