# Generated by Django 5.1.1 on 2024-09-26 15:54

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20240926_0756'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='User',
        #     name='groups',
        #     field=models.CharField(max_length=255, null=True, blank=True),
        # ),
    ]
