# Generated by Django 5.1.1 on 2024-09-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_grouppermission_group_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouppermissions', to='backend.module'),
        ),
    ]
